trigger:
- main

pool:
  vmImage: 'ubuntu 22.04'

stages:
  - stage: Run Maven jobs
    displayName: Build Maven Package
    jobs:
    - job: 
      displayName: Build Maven package
      steps:
      - task:
        inputs:
          mavenPOMFile: 'pom.xml'
          goals: package
          publishJunitResults: true
          testResultsFiles: '**/target/surefire-reports/*.xml'
          allowBrokenSymlinks: true
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: 1.17
          jdkArchitectureOption: x64
          mavenVersionOption: Default
          mavenOptions: '-Xmx1024m'
          sonarQubeRunAnalysis: false
          